### ISSUE TITLE
Faster development with Jetty plugin or alternative

### ISSUE THREAD

**Issue by iominh** [g00glen00b/spring-ng-chat#1]
Hi g00glen00b,

Thanks for your code and tutorial!

Have you tried or considered adding a Maven Jetty plugin for faster development? Instead of having to recompile and redeploy the app for front-end changes you could just refresh your browser and see the changes immediately.

For example, the following could be added to your pom.xml in the build section:

``` xml
<plugin>
  <groupId>org.eclipse.jetty</groupId>
  <artifactId>jetty-maven-plugin</artifactId>
  <version>9.2.11-SNAPSHOT</version>
</plugin>
```

Unfortunately, since your app doesn't have a web.xml and initializes it through code, the Maven Jetty plugin doesn't work unless you have Jetty 9 (Servlet 3.0) but for the life of me I can't seem to build the Jetty 9 Maven plugin because I can't seem to find the right repository that has it.

Alternatively, do you happen to have a web.xml that can be used instead of the WebAppInitializer? 

Any assistance would be appreciated, thanks!

**Comment by g00glen00b** [comment]
Well, you could go back to a web.xml file, however I'm pretty sure that if the web container does not support Servlet 3.0, most of it won't work. I did a quick search on Google and it seems that Jetty 7 and 8 do only support an early draft version of WebSockets (which is probably not compatible with the APIs necessary for Spring WebSockets to be working).

**Comment by iominh** [comment]
Thanks for the info, just in case anyone else runs across this, I ended up figuring out how to get the Maven Jetty9 running by looking at the Atmosphere samples (https://github.com/Atmosphere/atmosphere-samples). I'm not sure why I had so much trouble back then.
